export const VIDEOS = [
    {
        "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "title": "Building a Startup from Scratch: My Journey to $1M ARR",
        "description": "In this video, I share my complete journey of building a successful startup from zero to $1M ARR. I'll cover everything from the initial idea, finding co-founders, raising funding, building the product, acquiring customers, and scaling the business. Timestamps: 00:00 Introduction, 02:15 The Initial Idea, 05:30 Finding Co-founders, 08:45 Building MVP, 12:20 First Customers, 16:10 Raising Seed Round, 20:30 Scaling Challenges, 25:15 Reaching $1M ARR",
        "creatorName": "TechFounder",
        "creatorId": "creator-001",
        "tags": [
            "startup",
            "entrepreneurship",
            "business",
            "saas",
            "funding"
        ],
        "category": "Business",
        "duration": 1695,
        "viewCount": 1234567,
        "likeCount": 42834,
        "uploadTimestamp": 1704067200,
        "thumbnailUrl": "https://images.unsplash.com/photo-1551434678-e076c223a692?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/f47ac10b-startup-journey.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "550e8400-e29b-41d4-a716-446655440001",
        "title": "The Future of AI: What Every Developer Needs to Know",
        "description": "Artificial Intelligence is transforming software development. In this comprehensive guide, I break down the latest AI trends, tools, and techniques that every developer should understand in 2025. From GPT models to machine learning frameworks, we'll explore how AI will shape the future of coding.",
        "creatorName": "CodeWithSarah",
        "creatorId": "creator-002",
        "tags": [
            "ai",
            "artificial intelligence",
            "programming",
            "development",
            "future tech"
        ],
        "category": "Technology",
        "duration": 1102,
        "viewCount": 892341,
        "likeCount": 31245,
        "uploadTimestamp": 1704153600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/550e8400-ai-future.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
        "title": "React vs Vue vs Angular: Ultimate 2025 Comparison",
        "description": "Which JavaScript framework should you choose in 2025? I compare React, Vue, and Angular across performance, learning curve, job market, and ecosystem. Includes hands-on examples and real-world project considerations to help you make the right choice for your next project.",
        "creatorName": "DevMaster",
        "creatorId": "creator-003",
        "tags": [
            "react",
            "vue",
            "angular",
            "javascript",
            "frontend",
            "comparison"
        ],
        "category": "Technology",
        "duration": 1541,
        "viewCount": 567890,
        "likeCount": 23567,
        "uploadTimestamp": 1703808000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b810-frameworks-comparison.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b811-9dad-11d1-80b4-00c04fd430c9",
        "title": "How I Made $10K in My First Month as a Content Creator",
        "description": "Starting from zero subscribers, I'll show you exactly how I built a profitable content creation business in just 30 days. This isn't clickbait - I'll break down every revenue stream, from sponsorships to digital products, and share the exact strategies that worked.",
        "creatorName": "CreatorSuccess",
        "creatorId": "creator-004",
        "tags": [
            "content creation",
            "monetization",
            "income",
            "creator economy",
            "business"
        ],
        "category": "Business",
        "duration": 928,
        "viewCount": 2341567,
        "likeCount": 89234,
        "uploadTimestamp": 1703721600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b811-creator-income.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b812-9dad-11d1-80b4-00c04fd430ca",
        "title": "My Morning Routine That Changed Everything",
        "description": "After years of struggling with productivity, I developed a morning routine that completely transformed my life. In this video, I'll share the exact 7-step routine that helped me 10x my productivity, improve my health, and achieve better work-life balance.",
        "creatorName": "ProductivityPro",
        "creatorId": "creator-005",
        "tags": [
            "morning routine",
            "productivity",
            "habits",
            "self improvement",
            "lifestyle"
        ],
        "category": "Lifestyle",
        "duration": 495,
        "viewCount": 1456789,
        "likeCount": 67890,
        "uploadTimestamp": 1703462400,
        "thumbnailUrl": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b812-morning-routine.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b813-9dad-11d1-80b4-00c04fd430cb",
        "title": "Building My Dream Home Office Setup for $2000",
        "description": "Creating the perfect home office doesn't have to break the bank. I'll show you how I built an amazing workspace for under $2000, including desk setup, lighting, tech gear, and productivity tools. Full equipment list and links in the description!",
        "creatorName": "WorkspaceWizard",
        "creatorId": "creator-006",
        "tags": [
            "home office",
            "setup",
            "workspace",
            "productivity",
            "tech"
        ],
        "category": "Lifestyle",
        "duration": 1215,
        "viewCount": 789234,
        "likeCount": 34567,
        "uploadTimestamp": 1703376000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1586953135231-d8b95e038b7b?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b813-home-office.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b814-9dad-11d1-80b4-00c04fd430cc",
        "title": "The Psychology Behind Viral Content: What Actually Works",
        "description": "After analyzing 10,000+ viral videos, I've discovered the psychological triggers that make content spread. In this deep dive, I'll reveal the 5 key elements that make videos go viral and how you can apply these principles to your own content strategy.",
        "creatorName": "MarketingMind",
        "creatorId": "creator-007",
        "tags": [
            "viral content",
            "psychology",
            "marketing",
            "content strategy",
            "social media"
        ],
        "category": "Marketing",
        "duration": 710,
        "viewCount": 445678,
        "likeCount": 18923,
        "uploadTimestamp": 1704240000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b814-viral-psychology.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b815-9dad-11d1-80b4-00c04fd430cd",
        "title": "Why I Quit My 6-Figure Job to Become a YouTuber",
        "description": "Two years ago, I was making $150K as a software engineer. Today, I'm a full-time content creator earning twice that amount. Here's the complete story of why I made the switch, the challenges I faced, and lessons learned along the way.",
        "creatorName": "LifeTransitions",
        "creatorId": "creator-008",
        "tags": [
            "career change",
            "youtube",
            "life decisions",
            "personal story",
            "inspiration"
        ],
        "category": "Lifestyle",
        "duration": 873,
        "viewCount": 3456789,
        "likeCount": 145623,
        "uploadTimestamp": 1702857600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b815-career-change.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b816-9dad-11d1-80b4-00c04fd430ce",
        "title": "Master Python in 30 Days: Complete Beginner's Guide",
        "description": "Learn Python programming from absolute beginner to job-ready in just 30 days. This comprehensive course covers variables, functions, loops, classes, web scraping, data analysis, and building real projects. Perfect for career changers and coding bootcamp students.",
        "creatorName": "PythonMaster",
        "creatorId": "creator-009",
        "tags": [
            "python",
            "programming",
            "tutorial",
            "beginner",
            "coding",
            "education"
        ],
        "category": "Education",
        "duration": 2845,
        "viewCount": 1789234,
        "likeCount": 78945,
        "uploadTimestamp": 1703289600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b816-python-course.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b817-9dad-11d1-80b4-00c04fd430cf",
        "title": "Cryptocurrency Investment Strategy for 2025",
        "description": "With Bitcoin hitting new highs, here's my updated crypto investment strategy for 2025. I'll cover portfolio allocation, risk management, DeFi opportunities, and which altcoins I'm watching. Remember: this is not financial advice, always do your own research.",
        "creatorName": "CryptoGuru",
        "creatorId": "creator-010",
        "tags": [
            "cryptocurrency",
            "bitcoin",
            "investment",
            "finance",
            "trading",
            "defi"
        ],
        "category": "Finance",
        "duration": 1387,
        "viewCount": 567123,
        "likeCount": 23456,
        "uploadTimestamp": 1704326400,
        "thumbnailUrl": "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b817-crypto-strategy.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b818-9dad-11d1-80b4-00c04fd430d0",
        "title": "How to Build Muscle Fast: Science-Based Approach",
        "description": "Cut through the fitness BS with this evidence-based guide to building muscle efficiently. I'll cover optimal training frequency, progressive overload, nutrition timing, and recovery strategies backed by the latest research. Includes a free workout plan!",
        "creatorName": "FitnessScience",
        "creatorId": "creator-011",
        "tags": [
            "fitness",
            "muscle building",
            "workout",
            "nutrition",
            "science",
            "health"
        ],
        "category": "Health",
        "duration": 1234,
        "viewCount": 890456,
        "likeCount": 45678,
        "uploadTimestamp": 1703203200,
        "thumbnailUrl": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b818-muscle-building.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b819-9dad-11d1-80b4-00c04fd430d1",
        "title": "iPhone vs Android: Which Should You Choose in 2025?",
        "description": "The ultimate smartphone comparison for 2025. I'll compare the latest iPhones and Android flagships across cameras, performance, battery life, ecosystem, and value for money. Plus, I'll help you decide which platform is right for your needs and budget.",
        "creatorName": "TechReviewer",
        "creatorId": "creator-012",
        "tags": [
            "iphone",
            "android",
            "smartphone",
            "tech review",
            "comparison",
            "mobile"
        ],
        "category": "Technology",
        "duration": 1456,
        "viewCount": 2345678,
        "likeCount": 98765,
        "uploadTimestamp": 1704412800,
        "thumbnailUrl": "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b819-phone-comparison.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b820-9dad-11d1-80b4-00c04fd430d2",
        "title": "Mastering Time Management: GTD System That Actually Works",
        "description": "After trying dozens of productivity systems, I finally found one that works: Getting Things Done (GTD). In this tutorial, I'll show you how to implement David Allen's system using modern tools like Notion and Todoist to achieve stress-free productivity.",
        "creatorName": "ProductivityPro",
        "creatorId": "creator-005",
        "tags": [
            "time management",
            "gtd",
            "productivity",
            "organization",
            "systems",
            "notion"
        ],
        "category": "Productivity",
        "duration": 1823,
        "viewCount": 678912,
        "likeCount": 34567,
        "uploadTimestamp": 1703116800,
        "thumbnailUrl": "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b820-gtd-system.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b821-9dad-11d1-80b4-00c04fd430d3",
        "title": "Stock Market Crash Coming? My Preparation Strategy",
        "description": "With market volatility increasing, I'm sharing my strategy for preparing for a potential market downturn. I'll cover portfolio hedging, cash allocation, value investing opportunities, and how to stay calm during market chaos. Historical analysis included.",
        "creatorName": "InvestmentWise",
        "creatorId": "creator-013",
        "tags": [
            "stock market",
            "investing",
            "recession",
            "portfolio",
            "finance",
            "strategy"
        ],
        "category": "Finance",
        "duration": 1567,
        "viewCount": 456789,
        "likeCount": 19876,
        "uploadTimestamp": 1704499200,
        "thumbnailUrl": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b821-market-crash.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b822-9dad-11d1-80b4-00c04fd430d4",
        "title": "Cooking Italian Pasta Like a Pro: Chef's Secrets Revealed",
        "description": "Learn to cook authentic Italian pasta from a trained chef. I'll teach you how to make fresh pasta from scratch, perfect al dente cooking, and three classic sauces: Carbonara, Cacio e Pepe, and Amatriciana. Buon appetito!",
        "creatorName": "ChefMarco",
        "creatorId": "creator-014",
        "tags": [
            "cooking",
            "italian food",
            "pasta",
            "recipe",
            "chef",
            "food"
        ],
        "category": "Food",
        "duration": 1789,
        "viewCount": 1234567,
        "likeCount": 56789,
        "uploadTimestamp": 1703030400,
        "thumbnailUrl": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b822-italian-pasta.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b823-9dad-11d1-80b4-00c04fd430d5",
        "title": "Web3 and Blockchain Explained: Beyond the Hype",
        "description": "What is Web3 really? I break down blockchain technology, decentralized applications, NFTs, and the metaverse in simple terms. We'll explore real-world use cases, challenges, and whether Web3 is the future of the internet or just hype.",
        "creatorName": "BlockchainExplained",
        "creatorId": "creator-015",
        "tags": [
            "web3",
            "blockchain",
            "cryptocurrency",
            "nft",
            "decentralization",
            "technology"
        ],
        "category": "Technology",
        "duration": 2156,
        "viewCount": 789456,
        "likeCount": 32145,
        "uploadTimestamp": 1702944000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b823-web3-explained.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b824-9dad-11d1-80b4-00c04fd430d6",
        "title": "Learning Photography: From Beginner to Pro in 6 Months",
        "description": "My complete photography journey from knowing nothing to landing paid gigs. I'll share the exact learning path, gear recommendations, practice exercises, and how to build a portfolio that gets you hired. Includes free presets and cheat sheets!",
        "creatorName": "PhotoMaster",
        "creatorId": "creator-016",
        "tags": [
            "photography",
            "camera",
            "learning",
            "portfolio",
            "tutorial",
            "creative"
        ],
        "category": "Creative",
        "duration": 2034,
        "viewCount": 567890,
        "likeCount": 28945,
        "uploadTimestamp": 1703635200,
        "thumbnailUrl": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b824-photography-course.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b825-9dad-11d1-80b4-00c04fd430d7",
        "title": "Mental Health in Tech: Dealing with Burnout and Stress",
        "description": "Working in tech can be incredibly stressful. As someone who's experienced severe burnout, I want to share strategies for maintaining mental health, recognizing warning signs, and building sustainable work habits. Your mental health matters more than any deadline.",
        "creatorName": "TechWellness",
        "creatorId": "creator-017",
        "tags": [
            "mental health",
            "burnout",
            "stress",
            "tech industry",
            "wellness",
            "self care"
        ],
        "category": "Health",
        "duration": 1345,
        "viewCount": 445678,
        "likeCount": 23456,
        "uploadTimestamp": 1704585600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b825-tech-mental-health.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b826-9dad-11d1-80b4-00c04fd430d8",
        "title": "Electric Cars vs Gas Cars: Total Cost Analysis 2025",
        "description": "Are electric cars really cheaper? I break down the true cost of ownership including purchase price, charging vs gas, maintenance, insurance, and resale value. Plus, I'll help you decide if it's the right time to make the switch to electric.",
        "creatorName": "AutoExpert",
        "creatorId": "creator-018",
        "tags": [
            "electric cars",
            "tesla",
            "automotive",
            "cost analysis",
            "environment",
            "transportation"
        ],
        "category": "Automotive",
        "duration": 1678,
        "viewCount": 892345,
        "likeCount": 41256,
        "uploadTimestamp": 1703548800,
        "thumbnailUrl": "https://images.unsplash.com/photo-1593941707882-a5bac6861d75?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b826-electric-vs-gas.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b827-9dad-11d1-80b4-00c04fd430d9",
        "title": "Building a Gaming PC for $800 That Destroys Consoles",
        "description": "You don't need to spend $2000+ to build an amazing gaming PC. I'll show you how to build a budget gaming rig that outperforms PS5 and Xbox Series X for just $800. Complete build guide with benchmarks, part recommendations, and money-saving tips.",
        "creatorName": "PCBuildGuru",
        "creatorId": "creator-019",
        "tags": [
            "pc building",
            "gaming",
            "budget build",
            "computer",
            "hardware",
            "tutorial"
        ],
        "category": "Technology",
        "duration": 2234,
        "viewCount": 1567890,
        "likeCount": 67894,
        "uploadTimestamp": 1702771200,
        "thumbnailUrl": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b827-budget-gaming-pc.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b828-9dad-11d1-80b4-00c04fd430da",
        "title": "Real Estate Investing: My First Property Purchase Breakdown",
        "description": "I just bought my first investment property! In this video, I'll walk you through the entire process: finding deals, analyzing properties, securing financing, negotiating, and closing. Plus, I'll share my investment strategy and expected returns.",
        "creatorName": "RealEstateRookie",
        "creatorId": "creator-020",
        "tags": [
            "real estate",
            "investing",
            "property",
            "finance",
            "passive income",
            "wealth building"
        ],
        "category": "Finance",
        "duration": 1890,
        "viewCount": 345678,
        "likeCount": 15234,
        "uploadTimestamp": 1704672000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b828-first-property.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b829-9dad-11d1-80b4-00c04fd430db",
        "title": "Minimalism Changed My Life: 1 Year Later",
        "description": "One year ago, I embraced minimalism and got rid of 80% of my possessions. Here's what I learned: how minimalism affected my mental health, relationships, finances, and productivity. I'll share practical tips for anyone wanting to try a minimalist lifestyle.",
        "creatorName": "MinimalLife",
        "creatorId": "creator-021",
        "tags": [
            "minimalism",
            "lifestyle",
            "decluttering",
            "mental health",
            "simplicity",
            "mindfulness"
        ],
        "category": "Lifestyle",
        "duration": 1123,
        "viewCount": 789123,
        "likeCount": 38945,
        "uploadTimestamp": 1703721600,
        "thumbnailUrl": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b829-minimalism-year.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b830-9dad-11d1-80b4-00c04fd430dc",
        "title": "Docker and Kubernetes Explained: DevOps for Beginners",
        "description": "Confused by containers and orchestration? I'll explain Docker and Kubernetes in simple terms with hands-on examples. Perfect for developers wanting to understand modern DevOps practices. We'll build and deploy a real application using these tools.",
        "creatorName": "DevOpsSimplified",
        "creatorId": "creator-022",
        "tags": [
            "docker",
            "kubernetes",
            "devops",
            "containers",
            "deployment",
            "tutorial"
        ],
        "category": "Technology",
        "duration": 2456,
        "viewCount": 456789,
        "likeCount": 21345,
        "uploadTimestamp": 1703462400,
        "thumbnailUrl": "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b830-docker-kubernetes.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    },
    {
        "id": "6ba7b831-9dad-11d1-80b4-00c04fd430dd",
        "title": "Social Media Detox: 30 Days Without Instagram or TikTok",
        "description": "I deleted Instagram and TikTok for 30 days to see how it would affect my mental health, productivity, and relationships. The results surprised me. Here's what happened and whether I recommend trying a social media detox yourself.",
        "creatorName": "DigitalDetox",
        "creatorId": "creator-023",
        "tags": [
            "social media detox",
            "mental health",
            "instagram",
            "tiktok",
            "wellness",
            "digital minimalism"
        ],
        "category": "Health",
        "duration": 967,
        "viewCount": 1123456,
        "likeCount": 54321,
        "uploadTimestamp": 1704758400,
        "thumbnailUrl": "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b831-social-media-detox.mp4",
        "isVerifiedCreator": false,
        "language": "en"
    },
    {
        "id": "6ba7b832-9dad-11d1-80b4-00c04fd430de",
        "title": "Email Marketing That Actually Converts: My $100K Strategy",
        "description": "Email marketing generated $100K+ for my business last year. I'll share my complete email strategy including list building, automation sequences, segmentation, and copywriting techniques that convert. Plus, I'll reveal my highest-performing email templates.",
        "creatorName": "EmailMarketer",
        "creatorId": "creator-024",
        "tags": [
            "email marketing",
            "marketing automation",
            "copywriting",
            "business",
            "conversion",
            "sales"
        ],
        "category": "Marketing",
        "duration": 1723,
        "viewCount": 234567,
        "likeCount": 12345,
        "uploadTimestamp": 1703376000,
        "thumbnailUrl": "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=320&h=180&fit=crop",
        "videoUrl": "https://cdn.ventube.com/videos/6ba7b832-email-marketing.mp4",
        "isVerifiedCreator": true,
        "language": "en"
    }
]